Traceback (most recent call last):
  File "C:\Users\User\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\User\anaconda3\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\User\anaconda3\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\User\anaconda3\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\User\anaconda3\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\User\anaconda3\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\User\anaconda3\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\User\anaconda3\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
yhat_lava = lava_predict( X, Y.reshape(-1,1) )
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mValueError[0m                                Traceback (most recent call last)
Input [1;32mIn [11][0m, in [0;36m<cell line: 1>[1;34m()[0m
[1;32m----> 1[0m yhat_lava [38;5;241m=[39m [43mlava_predict[49m[43m([49m[43m [49m[43mX[49m[43m,[49m[43m [49m[43mY[49m[38;5;241;43m.[39;49m[43mreshape[49m[43m([49m[38;5;241;43m-[39;49m[38;5;241;43m1[39;49m[43m,[49m[38;5;241;43m1[39;49m[43m)[49m[43m [49m[43m)[49m

Input [1;32mIn [9][0m, in [0;36mlava_predict[1;34m(x, y, iteration)[0m
[0;32m     11[0m scaler[38;5;241m.[39mfit( new_dep_var_vec )
[0;32m     12[0m std_new_dep_var_vec [38;5;241m=[39m scaler[38;5;241m.[39mtransform( new_dep_var_vec )
[1;32m---> 14[0m fit_ridge_m1 [38;5;241m=[39m [43mElasticNetCV[49m[43m([49m[43m [49m[43mcv[49m[43m [49m[38;5;241;43m=[39;49m[43m [49m[38;5;241;43m10[39;49m[43m [49m[43m,[49m[43m [49m[43mnormalize[49m[43m [49m[38;5;241;43m=[39;49m[43m [49m[38;5;28;43;01mTrue[39;49;00m[43m [49m[43m,[49m[43m [49m[43mrandom_state[49m[43m [49m[38;5;241;43m=[39;49m[43m [49m[38;5;241;43m0[39;49m[43m [49m[43m,[49m[43m [49m[43ml1_ratio[49m[43m [49m[38;5;241;43m=[39;49m[43m [49m[38;5;241;43m0.0001[39;49m[43m,[49m[43m [49m[43malphas[49m[43m [49m[38;5;241;43m=[39;49m[43m [49m[43mnp[49m[38;5;241;43m.[39;49m[43marray[49m[43m([49m[43m[[49m[38;5;241;43m20[39;49m[43m][49m[43m)[49m[43m [49m[43m)[49m[38;5;241;43m.[39;49m[43mfit[49m[43m([49m[43m [49m[43mx[49m[43m,[49m[43m [49m[43mstd_new_dep_var_vec[49m[43m [49m[43m)[49m
[0;32m     15[0m m1 [38;5;241m=[39m scaler[38;5;241m.[39minverse_transform( fit_ridge_m1[38;5;241m.[39mpredict( x ) )
[0;32m     17[0m i [38;5;241m=[39m [38;5;241m1[39m

File [1;32m~\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:1564[0m, in [0;36mLinearModelCV.fit[1;34m(self, X, y, sample_weight)[0m
[0;32m   1559[0m     X, y [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_validate_data(
[0;32m   1560[0m         X, y, validate_separately[38;5;241m=[39m(check_X_params, check_y_params)
[0;32m   1561[0m     )
[0;32m   1562[0m     copy_X [38;5;241m=[39m [38;5;28;01mFalse[39;00m
[1;32m-> 1564[0m [43mcheck_consistent_length[49m[43m([49m[43mX[49m[43m,[49m[43m [49m[43my[49m[43m)[49m
[0;32m   1566[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28mself[39m[38;5;241m.[39m_is_multitask():
[0;32m   1567[0m     [38;5;28;01mif[39;00m y[38;5;241m.[39mndim [38;5;241m>[39m [38;5;241m1[39m [38;5;129;01mand[39;00m y[38;5;241m.[39mshape[[38;5;241m1[39m] [38;5;241m>[39m [38;5;241m1[39m:

File [1;32m~\anaconda3\lib\site-packages\sklearn\utils\validation.py:332[0m, in [0;36mcheck_consistent_length[1;34m(*arrays)[0m
[0;32m    330[0m uniques [38;5;241m=[39m np[38;5;241m.[39munique(lengths)
[0;32m    331[0m [38;5;28;01mif[39;00m [38;5;28mlen[39m(uniques) [38;5;241m>[39m [38;5;241m1[39m:
[1;32m--> 332[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[0;32m    333[0m         [38;5;124m"[39m[38;5;124mFound input variables with inconsistent numbers of samples: [39m[38;5;132;01m%r[39;00m[38;5;124m"[39m
[0;32m    334[0m         [38;5;241m%[39m [[38;5;28mint[39m(l) [38;5;28;01mfor[39;00m l [38;5;129;01min[39;00m lengths]
[0;32m    335[0m     )

[1;31mValueError[0m: Found input variables with inconsistent numbers of samples: [100, 10000]
ValueError: Found input variables with inconsistent numbers of samples: [100, 10000]

